<option value="aleksandrovac">Aleksandrovac</option>
<option value="aleksinac">Aleksinac</option>
<option value="arandjelovac">Aranđelovac</option>
<option value="backa-palanka">Bačka Palanka</option>
<option value="backa-topola">Bačka Topola</option>
<option value="bajina-basta">Bajina Bašta</option>
<option value="becej">Bečej</option>
<option value="beograd">Beograd</option>
<option value="blace">Blace</option>
<option value="bor">Bor</option>
<option value="bosilegrad">Bosilegrad</option>
<option value="brus">Brus</option>
<option value="cacak">Čačak</option>
<option value="despotovac">Despotovac</option>
<option value="dimitrovgrad">Dimitrovgrad</option>
<option value="golubac">Golubac</option>
<option value="gornji-milanovac">Gornji Milanovac</option>
<option value="indjija">Inđija</option>
<option value="irig">Irig</option>
<option value="ivanjica">Ivanjica</option>
<option value="jagodina">Jagodina</option>
<option value="kanjiza">Kanjiža</option>
<option value="kikinda">Kikinda</option>
<option value="kladovo">Kladovo</option>
<option value="knic">Knić</option>
<option value="knjazevac">Knjaževac</option>
<option value="kosjeric">Kosjerić</option>
<option value="kovacica">Kovačica</option>
<option value="kovin">Kovin</option>
<option value="kragujevac">Kragujevac</option>
<option value="kraljevo">Kraljevo</option>
<option value="krupanj">Krupanj</option>
<option value="krusevac">Kruševac</option>
<option value="kucevo">Kučevo</option>
<option value="kursumlija">Kuršumlija</option>
<option value="lajkovac">Lajkovac</option>
<option value="lapovo">Lapovo</option>
<option value="lebane">Lebane</option>
<option value="leskovac">Leskovac</option>
<option value="ljig">Ljig</option>
<option value="ljubovija">Ljubovija</option>
<option value="loznica">Loznica</option>
<option value="lucani">Lučani</option>
<option value="majdanpek">Majdanpek</option>
<option value="mali-zvornik">Mali Zvornik</option>
<option value="malo-crnice">Malo Crniće</option>
<option value="medvedja">Medveđa</option>
<option value="merosina">Merošina</option>
<option value="mionica">Mionica</option>
<option value="negotin">Negotin</option>
<option value="nis">Niš</option>
<option value="nova-crnja">Nova Crnja</option>
<option value="nova-varos">Nova Varoš</option>
<option value="novi-becej">Novi Bečej</option>
<option value="novi-knezevac">Novi Kneževac</option>
<option value="novi-pazar">Novi Pazar</option>
<option value="novi-sad">Novi Sad</option>
<option value="obrenovac">Obrenovac</option>
<option value="odzaci">Odžaci</option>
<option value="opovo">Opovo</option>
<option value="osecina">Osečina</option>
<option value="pancevo">Pančevo</option>
<option value="paracin">Paraćin</option>
<option value="pecinci">Pećinci</option>
<option value="petrovac-na-mlavi">Petrovac na Mlavi</option>
<option value="pirot">Pirot</option>
<option value="plandiste">Plandište</option>
<option value="pozarevac">Požarevac</option>
<option value="pozega">Požega</option>
<option value="presevo">Preševo</option>
<option value="priboj">Priboj</option>
<option value="prijepolje">Prijepolje</option>
<option value="prokuplje">Prokuplje</option>
<option value="raca">Rača</option>
<option value="raska">Raška</option>
<option value="razanj">Ražanj</option>
<option value="rekovac">Rekovac</option>
<option value="sabac">Šabac</option>
<option value="senta">Senta</option>
<option value="sid">Šid</option>
<option value="sjenica">Sjenica</option>
<option value="smederevo">Smederevo</option>
<option value="smederevska-palanka">Smederevska Palanka</option>
<option value="sokobanja">Sokobanja</option>
<option value="sombor">Sombor</option>
<option value="srbobran">Srbobran</option>
<option value="sremska-mitrovica">Sremska Mitrovica</option>
<option value="stara-pazova">Stara Pazova</option>
<option value="subotica">Subotica</option>
<option value="surdulica">Surdulica</option>
<option value="svilajnac">Svilajnac</option>
<option value="svrljig">Svrljig</option>
<option value="temerin">Temerin</option>
<option value="titel">Titel</option>
<option value="topola">Topola</option>
<option value="trgovište">Trgovište</option>
<option value="trstenik">Trstenik</option>
<option value="tutin">Tutin</option>
<option value="ub">Ub</option>
<option value="uzice">Užice</option>
<option value="valjevo">Valjevo</option>
<option value="varvarin">Varvarin</option>
<option value="velika-plana">Velika Plana</option>
<option value="veliko Gradište">Veliko Gradište</option>
<option value="vladicin-han">Vladičin Han</option>
<option value="vladimirci">Vladimirci</option>
<option value="vlasotince">Vlasotince</option>
<option value="vranje">Vranje</option>
<option value="vrbas">Vrbas</option>
<option value="vrnjačka Banja">Vrnjačka Banja</option>
<option value="vrsac">Vršac</option>
<option value="zabalj">Žabalj</option>
<option value="zabari">Žabari</option>
<option value="zagubica">Žagubica</option>
<option value="zajecar">Zaječar</option>
<option value="zitište">Žitište</option>
<option value="zitoradja">Žitorađa</option>
<option value="zlatar">Zlatar</option>
<option value="zlatibor">Zlatibor</option>
<option value="zrenjanin">Zrenjanin</option>