<option value="Aleksandrovac">Aleksandrovac</option>
<option value="Aleksinac">Aleksinac</option>
<option value="Aranđelovac">Aranđelovac</option>
<option value="Bačka Palanka">Bačka Palanka</option>
<option value="Bačka Topola">Bačka Topola</option>
<option value="Bajina Bašta">Bajina Bašta</option>
<option value="Bečej">Bečej</option>
<option value="Beograd">Beograd</option>
<option value="Blace">Blace</option>
<option value="Bor">Bor</option>
<option value="Bosilegrad">Bosilegrad</option>
<option value="Brus">Brus</option>
<option value="Čačak">Čačak</option>
<option value="Despotovac">Despotovac</option>
<option value="Dimitrovgrad">Dimitrovgrad</option>
<option value="Golubac">Golubac</option>
<option value="Gornji Milanovac">Gornji Milanovac</option>
<option value="Inđija">Inđija</option>
<option value="Irig">Irig</option>
<option value="Ivanjica">Ivanjica</option>
<option value="Jagodina">Jagodina</option>
<option value="Kanjiža">Kanjiža</option>
<option value="Kikinda">Kikinda</option>
<option value="Kladovo">Kladovo</option>
<option value="Knić">Knić</option>
<option value="Knjaževac">Knjaževac</option>
<option value="Kosjerić">Kosjerić</option>
<option value="Kovačica">Kovačica</option>
<option value="Kovin">Kovin</option>
<option value="Kragujevac">Kragujevac</option>
<option value="Kraljevo">Kraljevo</option>
<option value="Krupanj">Krupanj</option>
<option value="Kruševac">Kruševac</option>
<option value="Kučevo">Kučevo</option>
<option value="Kuršumlija">Kuršumlija</option>
<option value="Lajkovac">Lajkovac</option>
<option value="Lapovo">Lapovo</option>
<option value="Lebane">Lebane</option>
<option value="Leskovac">Leskovac</option>
<option value="Ljig">Ljig</option>
<option value="Ljubovija">Ljubovija</option>
<option value="Loznica">Loznica</option>
<option value="Lučani">Lučani</option>
<option value="Majdanpek">Majdanpek</option>
<option value="Mali Zvornik">Mali Zvornik</option>
<option value="Malo Crniće">Malo Crniće</option>
<option value="Medveđa">Medveđa</option>
<option value="Merošina">Merošina</option>
<option value="Mionica">Mionica</option>
<option value="Negotin">Negotin</option>
<option value="Niš">Niš</option>
<option value="Nova Crnja">Nova Crnja</option>
<option value="Nova Varoš">Nova Varoš</option>
<option value="Novi Bečej">Novi Bečej</option>
<option value="Novi Kneževac">Novi Kneževac</option>
<option value="Novi Pazar">Novi Pazar</option>
<option value="Novi Sad">Novi Sad</option>
<option value="Obrenovac">Obrenovac</option>
<option value="Odžaci">Odžaci</option>
<option value="Opovo">Opovo</option>
<option value="Osečina">Osečina</option>
<option value="Pančevo">Pančevo</option>
<option value="Paraćin">Paraćin</option>
<option value="Pećinci">Pećinci</option>
<option value="Petrovac na Mlavi">Petrovac na Mlavi</option>
<option value="Pirot">Pirot</option>
<option value="Plandište">Plandište</option>
<option value="Požarevac">Požarevac</option>
<option value="Požega">Požega</option>
<option value="Preševo">Preševo</option>
<option value="Priboj">Priboj</option>
<option value="Prijepolje">Prijepolje</option>
<option value="Prokuplje">Prokuplje</option>
<option value="Rača">Rača</option>
<option value="Raška">Raška</option>
<option value="Ražanj">Ražanj</option>
<option value="Rekovac">Rekovac</option>
<option value="Šabac">Šabac</option>
<option value="Senta">Senta</option>
<option value="Šid">Šid</option>
<option value="Sjenica">Sjenica</option>
<option value="Smederevo">Smederevo</option>
<option value="Smederevska Palanka">Smederevska Palanka</option>
<option value="Sokobanja">Sokobanja</option>
<option value="Sombor">Sombor</option>
<option value="Srbobran">Srbobran</option>
<option value="Sremska Mitrovica">Sremska Mitrovica</option>
<option value="Stara Pazova">Stara Pazova</option>
<option value="Subotica">Subotica</option>
<option value="Surdulica">Surdulica</option>
<option value="Svilajnac">Svilajnac</option>
<option value="Svrljig">Svrljig</option>
<option value="Temerin">Temerin</option>
<option value="Titel">Titel</option>
<option value="Topola">Topola</option>
<option value="Trgovište">Trgovište</option>
<option value="Trstenik">Trstenik</option>
<option value="Tutin">Tutin</option>
<option value="Ub">Ub</option>
<option value="Užice">Užice</option>
<option value="Valjevo">Valjevo</option>
<option value="Varvarin">Varvarin</option>
<option value="Velika Plana">Velika Plana</option>
<option value="Veliko Gradište">Veliko Gradište</option>
<option value="Vladičin Han">Vladičin Han</option>
<option value="Vladimirci">Vladimirci</option>
<option value="Vlasotince">Vlasotince</option>
<option value="Vranje">Vranje</option>
<option value="Vrbas">Vrbas</option>
<option value="Vrnjačka Banja">Vrnjačka Banja</option>
<option value="Vršac">Vršac</option>
<option value="Žabalj">Žabalj</option>
<option value="Žabari">Žabari</option>
<option value="Žagubica">Žagubica</option>
<option value="Zaječar">Zaječar</option>
<option value="Žitište">Žitište</option>
<option value="Žitorađa">Žitorađa</option>
<option value="Zlatar">Zlatar</option>
<option value="Zlatibor">Zlatibor</option>
<option value="Zrenjanin">Zrenjanin</option>