<?php
    class USERNAME_TAKEN_EXCEPTION extends Exception {}
    class WRONG_PASSWORD extends Exception {}
    class ACCOUNT_NOT_VERIFIED extends Exception {}
    class EMAIL_NOT_SENDED extends Exception {}
    class ACCOUNT_NOT_CREATED extends Exception {}
    class ERROR_FROM_QUERY extends Exception {}
    class OBJECT_USER_NOT_CREATED extends Exception {}
    class IS_EMAIL_TAKEN_ERROR extends Exception {}
    class IS_USERNAME_TAKEN_ERROR extends Exception {}
    class CREATE_PRIMARY_ERROR extends Exception {}
    class SET_OAUTH_UID_ERROR extends Exception {}
    class GET_ID_REGISTER_ERROR extends Exception {}
    class LOGIN_ERROR extends Exception {}
    class CHECK_USER_BY_OAUTH_UID_ERROR extends Exception {}
    class RETURN_OAUTH_UID_ERROR extends Exception {}
    class RETURN_USER_ERROR extends Exception {}
    class GET_EMAIL_ERROR extends Exception {}
    class UPDATE_USERNAME_ERROR extends Exception {}
    class RESET_PASSWORD_ERROR extends Exception {}
    class DELETE_RESET_PW_CODE_ERROR extends Exception {}
    class UPDATE_PASSWORD_ERROR extends Exception {}
    class CHECK_VERIFICATION_USER_EXIST extends Exception {}
    class SAVE_VERIFICATION_CODE_ERROR extends Exception {}
    class UPDATE_CHANGE_PW_CODE_ERROR extends Exception {}
    class UPDATE_VERIFICATION_CODE_ERROR extends Exception {}
    class VERIFY_USER_ERROR extends Exception {}
    class GET_USER_DATA_FROM_ID_ERROR extends Exception {}
    class GET_IP_ERROR extends Exception {}
    class MY_SAVES_ERROR extends Exception {}
?>